/var/spool/slurmd/job1606889/slurm_script: line 12: ------------------------: command not found
Traceback (most recent call last):
  File "/data/srlab/ssg34/SLE_kidney_v2/sugiarto_scripts/CNA_chronicityPT/chronicityCNA.py", line 16, in <module>
    harmony = pd.read_csv(('ptChronicities/' + name + '/sc_harmony.csv'))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/PHShome/ns013/miniconda3/envs/CTAPs/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1024, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/PHShome/ns013/miniconda3/envs/CTAPs/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 618, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/PHShome/ns013/miniconda3/envs/CTAPs/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1618, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/PHShome/ns013/miniconda3/envs/CTAPs/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1878, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/PHShome/ns013/miniconda3/envs/CTAPs/lib/python3.11/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'ptChronicities/PT/sc_harmony.csv'
